export {default as Header} from "./Header";
export {default as Categories} from "./Catigories";
export {default as Button} from "./Button";
export {default as SortPopup} from "./SortPopup";
export {default as Home} from "../Pages/Home";
export {default as Cart} from "../Pages/Cart";
export {default as PizzaBlock} from "./PizzaBlock";
export {default as PizzaLoadingBlock} from "./PizzaBlock/LoadingBlock";
export {default as CartItem} from "./CartItem";